version: '3'
services:
  ubuntu-ddes:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - ubuntu-net
networks:
  ubuntu-net:
    driver: bridge