version: '3'
services:
  ubuntu-ddes:
    image: ubuntu:latest
    command: tail -f /dev/null  # Keeps the container running
    stdin_open: true
    tty: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - ubuntu-net
networks:
  ubuntu-net:
    driver: bridge